//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЖюриАктивностей
    {
        public int ActivityID { get; set; }
        public int JuryID { get; set; }
        public int ID { get; set; }
    
        public virtual Активности Активности { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
