//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.ЖюриАктивностей = new HashSet<ЖюриАктивностей>();
        }
    
        public int ID { get; set; }
        public string FIO { get; set; }
        public int GenderID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string PhoneNumber { get; set; }
        public string Direction { get; set; }
        public string Event { get; set; }
        public string Password { get; set; }
        public string PhotoPath { get; set; }
        public int RoleID { get; set; }
    
        public virtual Cтраны Cтраны { get; set; }
        public virtual Пол Пол { get; set; }
        public virtual Роли Роли { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖюриАктивностей> ЖюриАктивностей { get; set; }
    }
}
